project_id = "eugvjubeuyukhgcwfncr"

[functions.scrape-barchart-options]
verify_jwt = false

[functions.scrape-barchart-symbols]
verify_jwt = false

[functions.scrape-barchart-futures]
verify_jwt = false

[functions.scrape-barchart-maturities]
verify_jwt = false
