project_id = "iflnsckduohrcafafcpj"

[functions.scrape-barchart-options]
verify_jwt = false

[functions.scrape-barchart-symbols]
verify_jwt = false

[functions.scrape-barchart-futures]
verify_jwt = false

[functions.scrape-barchart-maturities]
verify_jwt = false

[functions.scrape-tradingview-symbols]
verify_jwt = false

[functions.scrape-tradingview-futures]
verify_jwt = false

[functions.scrape-tradingview-options]
verify_jwt = false

[functions.scrape-forex-symbols]
verify_jwt = false

[functions.scrape-forex-futures]
verify_jwt = false

[functions.scrape-forex-options]
verify_jwt = false

[functions.scrape-tv-forex-symbols]
verify_jwt = false

[functions.scrape-tv-forex-futures]
verify_jwt = false

[functions.scrape-tv-forex-options]
verify_jwt = false

[functions.get-strikes]
verify_jwt = false
